name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci --prefix ./sample-packages/npm
      - run: npm test --prefix ./sample-packages/npm

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --prefix ./sample-packages/npm
      - run: npm publish --prefix ./sample-packages/npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
